// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.aquasec.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumiverse.aquasec.outputs.GetApplicationScopeCategoryInfrastructureOVariable;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetApplicationScopeCategoryInfrastructureO {
    private String expression;
    private @Nullable List<GetApplicationScopeCategoryInfrastructureOVariable> variables;

    private GetApplicationScopeCategoryInfrastructureO() {}
    public String expression() {
        return this.expression;
    }
    public List<GetApplicationScopeCategoryInfrastructureOVariable> variables() {
        return this.variables == null ? List.of() : this.variables;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetApplicationScopeCategoryInfrastructureO defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String expression;
        private @Nullable List<GetApplicationScopeCategoryInfrastructureOVariable> variables;
        public Builder() {}
        public Builder(GetApplicationScopeCategoryInfrastructureO defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.expression = defaults.expression;
    	      this.variables = defaults.variables;
        }

        @CustomType.Setter
        public Builder expression(String expression) {
            this.expression = Objects.requireNonNull(expression);
            return this;
        }
        @CustomType.Setter
        public Builder variables(@Nullable List<GetApplicationScopeCategoryInfrastructureOVariable> variables) {
            this.variables = variables;
            return this;
        }
        public Builder variables(GetApplicationScopeCategoryInfrastructureOVariable... variables) {
            return variables(List.of(variables));
        }
        public GetApplicationScopeCategoryInfrastructureO build() {
            final var o = new GetApplicationScopeCategoryInfrastructureO();
            o.expression = expression;
            o.variables = variables;
            return o;
        }
    }
}
