version: 2
archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'

before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-aquasec
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/pulumiverse/pulumi-aquasec/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-aquasec/

changelog:
  skip: true

release:
  disable: false
  prerelease: auto

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
