// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Aquasec
{
    public static class GetHostRuntimePolicy
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Aquasec = Pulumi.Aquasec;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var hostRuntimePolicy = Aquasec.GetHostRuntimePolicy.Invoke(new()
        ///     {
        ///         Name = "hostRuntimePolicyName",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["hostRuntimePolicyDetails"] = hostRuntimePolicy,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetHostRuntimePolicyResult> InvokeAsync(GetHostRuntimePolicyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHostRuntimePolicyResult>("aquasec:index/getHostRuntimePolicy:getHostRuntimePolicy", args ?? new GetHostRuntimePolicyArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Aquasec = Pulumi.Aquasec;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var hostRuntimePolicy = Aquasec.GetHostRuntimePolicy.Invoke(new()
        ///     {
        ///         Name = "hostRuntimePolicyName",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["hostRuntimePolicyDetails"] = hostRuntimePolicy,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetHostRuntimePolicyResult> Invoke(GetHostRuntimePolicyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHostRuntimePolicyResult>("aquasec:index/getHostRuntimePolicy:getHostRuntimePolicy", args ?? new GetHostRuntimePolicyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHostRuntimePolicyArgs : global::Pulumi.InvokeArgs
    {
        [Input("auditing")]
        public Inputs.GetHostRuntimePolicyAuditingArgs? Auditing { get; set; }

        [Input("fileIntegrityMonitorings")]
        private List<Inputs.GetHostRuntimePolicyFileIntegrityMonitoringArgs>? _fileIntegrityMonitorings;

        /// <summary>
        /// Configuration for file integrity monitoring.
        /// </summary>
        public List<Inputs.GetHostRuntimePolicyFileIntegrityMonitoringArgs> FileIntegrityMonitorings
        {
            get => _fileIntegrityMonitorings ?? (_fileIntegrityMonitorings = new List<Inputs.GetHostRuntimePolicyFileIntegrityMonitoringArgs>());
            set => _fileIntegrityMonitorings = value;
        }

        [Input("malwareScanOptions")]
        private List<Inputs.GetHostRuntimePolicyMalwareScanOptionArgs>? _malwareScanOptions;

        /// <summary>
        /// Configuration for Real-Time Malware Protection.
        /// </summary>
        public List<Inputs.GetHostRuntimePolicyMalwareScanOptionArgs> MalwareScanOptions
        {
            get => _malwareScanOptions ?? (_malwareScanOptions = new List<Inputs.GetHostRuntimePolicyMalwareScanOptionArgs>());
            set => _malwareScanOptions = value;
        }

        /// <summary>
        /// Name of the host runtime policy
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("packageBlocks")]
        private List<Inputs.GetHostRuntimePolicyPackageBlockArgs>? _packageBlocks;
        public List<Inputs.GetHostRuntimePolicyPackageBlockArgs> PackageBlocks
        {
            get => _packageBlocks ?? (_packageBlocks = new List<Inputs.GetHostRuntimePolicyPackageBlockArgs>());
            set => _packageBlocks = value;
        }

        public GetHostRuntimePolicyArgs()
        {
        }
        public static new GetHostRuntimePolicyArgs Empty => new GetHostRuntimePolicyArgs();
    }

    public sealed class GetHostRuntimePolicyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("auditing")]
        public Input<Inputs.GetHostRuntimePolicyAuditingInputArgs>? Auditing { get; set; }

        [Input("fileIntegrityMonitorings")]
        private InputList<Inputs.GetHostRuntimePolicyFileIntegrityMonitoringInputArgs>? _fileIntegrityMonitorings;

        /// <summary>
        /// Configuration for file integrity monitoring.
        /// </summary>
        public InputList<Inputs.GetHostRuntimePolicyFileIntegrityMonitoringInputArgs> FileIntegrityMonitorings
        {
            get => _fileIntegrityMonitorings ?? (_fileIntegrityMonitorings = new InputList<Inputs.GetHostRuntimePolicyFileIntegrityMonitoringInputArgs>());
            set => _fileIntegrityMonitorings = value;
        }

        [Input("malwareScanOptions")]
        private InputList<Inputs.GetHostRuntimePolicyMalwareScanOptionInputArgs>? _malwareScanOptions;

        /// <summary>
        /// Configuration for Real-Time Malware Protection.
        /// </summary>
        public InputList<Inputs.GetHostRuntimePolicyMalwareScanOptionInputArgs> MalwareScanOptions
        {
            get => _malwareScanOptions ?? (_malwareScanOptions = new InputList<Inputs.GetHostRuntimePolicyMalwareScanOptionInputArgs>());
            set => _malwareScanOptions = value;
        }

        /// <summary>
        /// Name of the host runtime policy
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("packageBlocks")]
        private InputList<Inputs.GetHostRuntimePolicyPackageBlockInputArgs>? _packageBlocks;
        public InputList<Inputs.GetHostRuntimePolicyPackageBlockInputArgs> PackageBlocks
        {
            get => _packageBlocks ?? (_packageBlocks = new InputList<Inputs.GetHostRuntimePolicyPackageBlockInputArgs>());
            set => _packageBlocks = value;
        }

        public GetHostRuntimePolicyInvokeArgs()
        {
        }
        public static new GetHostRuntimePolicyInvokeArgs Empty => new GetHostRuntimePolicyInvokeArgs();
    }


    [OutputType]
    public sealed class GetHostRuntimePolicyResult
    {
        /// <summary>
        /// Indicates the application scope of the service.
        /// </summary>
        public readonly ImmutableArray<string> ApplicationScopes;
        /// <summary>
        /// If true, all process activity will be audited.
        /// </summary>
        public readonly bool AuditAllOsUserActivity;
        /// <summary>
        /// Detects brute force login attempts
        /// </summary>
        public readonly bool AuditBruteForceLogin;
        /// <summary>
        /// If true, full command arguments will be audited.
        /// </summary>
        public readonly bool AuditFullCommandArguments;
        /// <summary>
        /// If true, host failed logins will be audited.
        /// </summary>
        public readonly bool AuditHostFailedLoginEvents;
        /// <summary>
        /// If true, host successful logins will be audited.
        /// </summary>
        public readonly bool AuditHostSuccessfulLoginEvents;
        /// <summary>
        /// If true, account management will be audited.
        /// </summary>
        public readonly bool AuditUserAccountManagement;
        public readonly Outputs.GetHostRuntimePolicyAuditingResult? Auditing;
        /// <summary>
        /// Username of the account that created the service.
        /// </summary>
        public readonly string Author;
        /// <summary>
        /// Detect and prevent communication to DNS/IP addresses known to be used for Cryptocurrency Mining
        /// </summary>
        public readonly bool BlockCryptocurrencyMining;
        /// <summary>
        /// List of files that are prevented from being read, modified and executed in the containers.
        /// </summary>
        public readonly ImmutableArray<string> BlockedFiles;
        /// <summary>
        /// The description of the host runtime policy
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// If true, detect and prevent communication from containers to IP addresses known to have a bad reputation.
        /// </summary>
        public readonly bool EnableIpReputation;
        /// <summary>
        /// Indicates if the runtime policy is enabled or not.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Indicates that policy should effect container execution (not just for audit).
        /// </summary>
        public readonly bool Enforce;
        /// <summary>
        /// Indicates the number of days after which the runtime policy will be changed to enforce mode.
        /// </summary>
        public readonly int EnforceAfterDays;
        /// <summary>
        /// Configuration for file integrity monitoring.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetHostRuntimePolicyFileIntegrityMonitoringResult> FileIntegrityMonitorings;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Configuration for Real-Time Malware Protection.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetHostRuntimePolicyMalwareScanOptionResult> MalwareScanOptions;
        /// <summary>
        /// If true, system log will be monitored.
        /// </summary>
        public readonly bool MonitorSystemLogIntegrity;
        /// <summary>
        /// If true, system time changes will be monitored.
        /// </summary>
        public readonly bool MonitorSystemTimeChanges;
        /// <summary>
        /// If true, windows service operations will be monitored.
        /// </summary>
        public readonly bool MonitorWindowsServices;
        /// <summary>
        /// Name of the host runtime policy
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// List of OS (Linux or Windows) groups that are allowed to authenticate to the host, and block authentication requests from all others. Groups can be either Linux groups or Windows AD groups.
        /// </summary>
        public readonly ImmutableArray<string> OsGroupsAlloweds;
        /// <summary>
        /// List of OS (Linux or Windows) groups that are not allowed to authenticate to the host, and block authentication requests from all others. Groups can be either Linux groups or Windows AD groups.
        /// </summary>
        public readonly ImmutableArray<string> OsGroupsBlockeds;
        /// <summary>
        /// List of OS (Linux or Windows) users that are allowed to authenticate to the host, and block authentication requests from all others.
        /// </summary>
        public readonly ImmutableArray<string> OsUsersAlloweds;
        /// <summary>
        /// List of OS (Linux or Windows) users that are not allowed to authenticate to the host, and block authentication requests from all others.
        /// </summary>
        public readonly ImmutableArray<string> OsUsersBlockeds;
        public readonly ImmutableArray<Outputs.GetHostRuntimePolicyPackageBlockResult> PackageBlocks;
        /// <summary>
        /// If true, port scanning behaviors will be audited.
        /// </summary>
        public readonly bool PortScanningDetection;
        /// <summary>
        /// Logical expression of how to compute the dependency of the scope variables.
        /// </summary>
        public readonly string ScopeExpression;
        /// <summary>
        /// List of scope attributes.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetHostRuntimePolicyScopeVariableResult> ScopeVariables;
        /// <summary>
        /// Configuration for windows registry monitoring.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetHostRuntimePolicyWindowsRegistryMonitoringResult> WindowsRegistryMonitorings;
        /// <summary>
        /// Configuration for windows registry protection.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetHostRuntimePolicyWindowsRegistryProtectionResult> WindowsRegistryProtections;

        [OutputConstructor]
        private GetHostRuntimePolicyResult(
            ImmutableArray<string> applicationScopes,

            bool auditAllOsUserActivity,

            bool auditBruteForceLogin,

            bool auditFullCommandArguments,

            bool auditHostFailedLoginEvents,

            bool auditHostSuccessfulLoginEvents,

            bool auditUserAccountManagement,

            Outputs.GetHostRuntimePolicyAuditingResult? auditing,

            string author,

            bool blockCryptocurrencyMining,

            ImmutableArray<string> blockedFiles,

            string description,

            bool enableIpReputation,

            bool enabled,

            bool enforce,

            int enforceAfterDays,

            ImmutableArray<Outputs.GetHostRuntimePolicyFileIntegrityMonitoringResult> fileIntegrityMonitorings,

            string id,

            ImmutableArray<Outputs.GetHostRuntimePolicyMalwareScanOptionResult> malwareScanOptions,

            bool monitorSystemLogIntegrity,

            bool monitorSystemTimeChanges,

            bool monitorWindowsServices,

            string name,

            ImmutableArray<string> osGroupsAlloweds,

            ImmutableArray<string> osGroupsBlockeds,

            ImmutableArray<string> osUsersAlloweds,

            ImmutableArray<string> osUsersBlockeds,

            ImmutableArray<Outputs.GetHostRuntimePolicyPackageBlockResult> packageBlocks,

            bool portScanningDetection,

            string scopeExpression,

            ImmutableArray<Outputs.GetHostRuntimePolicyScopeVariableResult> scopeVariables,

            ImmutableArray<Outputs.GetHostRuntimePolicyWindowsRegistryMonitoringResult> windowsRegistryMonitorings,

            ImmutableArray<Outputs.GetHostRuntimePolicyWindowsRegistryProtectionResult> windowsRegistryProtections)
        {
            ApplicationScopes = applicationScopes;
            AuditAllOsUserActivity = auditAllOsUserActivity;
            AuditBruteForceLogin = auditBruteForceLogin;
            AuditFullCommandArguments = auditFullCommandArguments;
            AuditHostFailedLoginEvents = auditHostFailedLoginEvents;
            AuditHostSuccessfulLoginEvents = auditHostSuccessfulLoginEvents;
            AuditUserAccountManagement = auditUserAccountManagement;
            Auditing = auditing;
            Author = author;
            BlockCryptocurrencyMining = blockCryptocurrencyMining;
            BlockedFiles = blockedFiles;
            Description = description;
            EnableIpReputation = enableIpReputation;
            Enabled = enabled;
            Enforce = enforce;
            EnforceAfterDays = enforceAfterDays;
            FileIntegrityMonitorings = fileIntegrityMonitorings;
            Id = id;
            MalwareScanOptions = malwareScanOptions;
            MonitorSystemLogIntegrity = monitorSystemLogIntegrity;
            MonitorSystemTimeChanges = monitorSystemTimeChanges;
            MonitorWindowsServices = monitorWindowsServices;
            Name = name;
            OsGroupsAlloweds = osGroupsAlloweds;
            OsGroupsBlockeds = osGroupsBlockeds;
            OsUsersAlloweds = osUsersAlloweds;
            OsUsersBlockeds = osUsersBlockeds;
            PackageBlocks = packageBlocks;
            PortScanningDetection = portScanningDetection;
            ScopeExpression = scopeExpression;
            ScopeVariables = scopeVariables;
            WindowsRegistryMonitorings = windowsRegistryMonitorings;
            WindowsRegistryProtections = windowsRegistryProtections;
        }
    }
}
