// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.aquasec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EnforcerGroupsOrchestratorArgs extends com.pulumi.resources.ResourceArgs {

    public static final EnforcerGroupsOrchestratorArgs Empty = new EnforcerGroupsOrchestratorArgs();

    @Import(name="master")
    private @Nullable Output<Boolean> master;

    public Optional<Output<Boolean>> master() {
        return Optional.ofNullable(this.master);
    }

    /**
     * May be specified for these orchestrators: Kubernetes, Kubernetes GKE, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return May be specified for these orchestrators: Kubernetes, Kubernetes GKE, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * May be specified for these orchestrators: Kubernetes, Kubernetes GKE, OpenShift, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
     * 
     */
    @Import(name="serviceAccount")
    private @Nullable Output<String> serviceAccount;

    /**
     * @return May be specified for these orchestrators: Kubernetes, Kubernetes GKE, OpenShift, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
     * 
     */
    public Optional<Output<String>> serviceAccount() {
        return Optional.ofNullable(this.serviceAccount);
    }

    /**
     * Enforcer Type.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Enforcer Type.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private EnforcerGroupsOrchestratorArgs() {}

    private EnforcerGroupsOrchestratorArgs(EnforcerGroupsOrchestratorArgs $) {
        this.master = $.master;
        this.namespace = $.namespace;
        this.serviceAccount = $.serviceAccount;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EnforcerGroupsOrchestratorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EnforcerGroupsOrchestratorArgs $;

        public Builder() {
            $ = new EnforcerGroupsOrchestratorArgs();
        }

        public Builder(EnforcerGroupsOrchestratorArgs defaults) {
            $ = new EnforcerGroupsOrchestratorArgs(Objects.requireNonNull(defaults));
        }

        public Builder master(@Nullable Output<Boolean> master) {
            $.master = master;
            return this;
        }

        public Builder master(Boolean master) {
            return master(Output.of(master));
        }

        /**
         * @param namespace May be specified for these orchestrators: Kubernetes, Kubernetes GKE, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace May be specified for these orchestrators: Kubernetes, Kubernetes GKE, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param serviceAccount May be specified for these orchestrators: Kubernetes, Kubernetes GKE, OpenShift, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
         * 
         * @return builder
         * 
         */
        public Builder serviceAccount(@Nullable Output<String> serviceAccount) {
            $.serviceAccount = serviceAccount;
            return this;
        }

        /**
         * @param serviceAccount May be specified for these orchestrators: Kubernetes, Kubernetes GKE, OpenShift, VMware Tanzu Kubernetes Grid Integrated Edition (PKS).
         * 
         * @return builder
         * 
         */
        public Builder serviceAccount(String serviceAccount) {
            return serviceAccount(Output.of(serviceAccount));
        }

        /**
         * @param type Enforcer Type.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Enforcer Type.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public EnforcerGroupsOrchestratorArgs build() {
            return $;
        }
    }

}
