// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.aquasec.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetApplicationScopeCategoryEntityScopeVariable extends com.pulumi.resources.InvokeArgs {

    public static final GetApplicationScopeCategoryEntityScopeVariable Empty = new GetApplicationScopeCategoryEntityScopeVariable();

    @Import(name="attribute", required=true)
    private String attribute;

    public String attribute() {
        return this.attribute;
    }

    @Import(name="value", required=true)
    private String value;

    public String value() {
        return this.value;
    }

    private GetApplicationScopeCategoryEntityScopeVariable() {}

    private GetApplicationScopeCategoryEntityScopeVariable(GetApplicationScopeCategoryEntityScopeVariable $) {
        this.attribute = $.attribute;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetApplicationScopeCategoryEntityScopeVariable defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetApplicationScopeCategoryEntityScopeVariable $;

        public Builder() {
            $ = new GetApplicationScopeCategoryEntityScopeVariable();
        }

        public Builder(GetApplicationScopeCategoryEntityScopeVariable defaults) {
            $ = new GetApplicationScopeCategoryEntityScopeVariable(Objects.requireNonNull(defaults));
        }

        public Builder attribute(String attribute) {
            $.attribute = attribute;
            return this;
        }

        public Builder value(String value) {
            $.value = value;
            return this;
        }

        public GetApplicationScopeCategoryEntityScopeVariable build() {
            $.attribute = Objects.requireNonNull($.attribute, "expected parameter 'attribute' to be non-null");
            $.value = Objects.requireNonNull($.value, "expected parameter 'value' to be non-null");
            return $;
        }
    }

}
