// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.aquasec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumiverse.aquasec.inputs.GetApplicationScopeCategoryWorkloadOVariableArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetApplicationScopeCategoryWorkloadOArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetApplicationScopeCategoryWorkloadOArgs Empty = new GetApplicationScopeCategoryWorkloadOArgs();

    @Import(name="expression", required=true)
    private Output<String> expression;

    public Output<String> expression() {
        return this.expression;
    }

    @Import(name="variables")
    private @Nullable Output<List<GetApplicationScopeCategoryWorkloadOVariableArgs>> variables;

    public Optional<Output<List<GetApplicationScopeCategoryWorkloadOVariableArgs>>> variables() {
        return Optional.ofNullable(this.variables);
    }

    private GetApplicationScopeCategoryWorkloadOArgs() {}

    private GetApplicationScopeCategoryWorkloadOArgs(GetApplicationScopeCategoryWorkloadOArgs $) {
        this.expression = $.expression;
        this.variables = $.variables;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetApplicationScopeCategoryWorkloadOArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetApplicationScopeCategoryWorkloadOArgs $;

        public Builder() {
            $ = new GetApplicationScopeCategoryWorkloadOArgs();
        }

        public Builder(GetApplicationScopeCategoryWorkloadOArgs defaults) {
            $ = new GetApplicationScopeCategoryWorkloadOArgs(Objects.requireNonNull(defaults));
        }

        public Builder expression(Output<String> expression) {
            $.expression = expression;
            return this;
        }

        public Builder expression(String expression) {
            return expression(Output.of(expression));
        }

        public Builder variables(@Nullable Output<List<GetApplicationScopeCategoryWorkloadOVariableArgs>> variables) {
            $.variables = variables;
            return this;
        }

        public Builder variables(List<GetApplicationScopeCategoryWorkloadOVariableArgs> variables) {
            return variables(Output.of(variables));
        }

        public Builder variables(GetApplicationScopeCategoryWorkloadOVariableArgs... variables) {
            return variables(List.of(variables));
        }

        public GetApplicationScopeCategoryWorkloadOArgs build() {
            $.expression = Objects.requireNonNull($.expression, "expected parameter 'expression' to be non-null");
            return $;
        }
    }

}
