// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.aquasec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetApplicationScopeCategoryArtifactCfVariableArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetApplicationScopeCategoryArtifactCfVariableArgs Empty = new GetApplicationScopeCategoryArtifactCfVariableArgs();

    @Import(name="attribute", required=true)
    private Output<String> attribute;

    public Output<String> attribute() {
        return this.attribute;
    }

    @Import(name="value")
    private @Nullable Output<String> value;

    public Optional<Output<String>> value() {
        return Optional.ofNullable(this.value);
    }

    private GetApplicationScopeCategoryArtifactCfVariableArgs() {}

    private GetApplicationScopeCategoryArtifactCfVariableArgs(GetApplicationScopeCategoryArtifactCfVariableArgs $) {
        this.attribute = $.attribute;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetApplicationScopeCategoryArtifactCfVariableArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetApplicationScopeCategoryArtifactCfVariableArgs $;

        public Builder() {
            $ = new GetApplicationScopeCategoryArtifactCfVariableArgs();
        }

        public Builder(GetApplicationScopeCategoryArtifactCfVariableArgs defaults) {
            $ = new GetApplicationScopeCategoryArtifactCfVariableArgs(Objects.requireNonNull(defaults));
        }

        public Builder attribute(Output<String> attribute) {
            $.attribute = attribute;
            return this;
        }

        public Builder attribute(String attribute) {
            return attribute(Output.of(attribute));
        }

        public Builder value(@Nullable Output<String> value) {
            $.value = value;
            return this;
        }

        public Builder value(String value) {
            return value(Output.of(value));
        }

        public GetApplicationScopeCategoryArtifactCfVariableArgs build() {
            $.attribute = Objects.requireNonNull($.attribute, "expected parameter 'attribute' to be non-null");
            return $;
        }
    }

}
