// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Aquasec.Inputs
{

    public sealed class GetContainerRuntimePolicyReadonlyFilesArgs : global::Pulumi.InvokeArgs
    {
        [Input("enabled")]
        public bool? Enabled { get; set; }

        [Input("exceptionalReadonlyFiles")]
        private List<string>? _exceptionalReadonlyFiles;
        public List<string> ExceptionalReadonlyFiles
        {
            get => _exceptionalReadonlyFiles ?? (_exceptionalReadonlyFiles = new List<string>());
            set => _exceptionalReadonlyFiles = value;
        }

        [Input("exceptionalReadonlyFilesProcesses")]
        private List<string>? _exceptionalReadonlyFilesProcesses;
        public List<string> ExceptionalReadonlyFilesProcesses
        {
            get => _exceptionalReadonlyFilesProcesses ?? (_exceptionalReadonlyFilesProcesses = new List<string>());
            set => _exceptionalReadonlyFilesProcesses = value;
        }

        [Input("exceptionalReadonlyFilesUsers")]
        private List<string>? _exceptionalReadonlyFilesUsers;
        public List<string> ExceptionalReadonlyFilesUsers
        {
            get => _exceptionalReadonlyFilesUsers ?? (_exceptionalReadonlyFilesUsers = new List<string>());
            set => _exceptionalReadonlyFilesUsers = value;
        }

        [Input("readonlyFiles")]
        private List<string>? _readonlyFiles;
        public List<string> ReadonlyFiles
        {
            get => _readonlyFiles ?? (_readonlyFiles = new List<string>());
            set => _readonlyFiles = value;
        }

        [Input("readonlyFilesProcesses")]
        private List<string>? _readonlyFilesProcesses;
        public List<string> ReadonlyFilesProcesses
        {
            get => _readonlyFilesProcesses ?? (_readonlyFilesProcesses = new List<string>());
            set => _readonlyFilesProcesses = value;
        }

        [Input("readonlyFilesUsers")]
        private List<string>? _readonlyFilesUsers;
        public List<string> ReadonlyFilesUsers
        {
            get => _readonlyFilesUsers ?? (_readonlyFilesUsers = new List<string>());
            set => _readonlyFilesUsers = value;
        }

        public GetContainerRuntimePolicyReadonlyFilesArgs()
        {
        }
        public static new GetContainerRuntimePolicyReadonlyFilesArgs Empty => new GetContainerRuntimePolicyReadonlyFilesArgs();
    }
}
