// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/** @deprecated aquasec.index/getintegrationregistry.getIntegrationRegistry has been deprecated in favor of aquasec.index/getintegrationregistries.getIntegrationRegistries */
export function getIntegrationRegistry(args: GetIntegrationRegistryArgs, opts?: pulumi.InvokeOptions): Promise<GetIntegrationRegistryResult> {
    pulumi.log.warn("getIntegrationRegistry is deprecated: aquasec.index/getintegrationregistry.getIntegrationRegistry has been deprecated in favor of aquasec.index/getintegrationregistries.getIntegrationRegistries")

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aquasec:index/getIntegrationRegistry:getIntegrationRegistry", {
        "advancedSettingsCleanup": args.advancedSettingsCleanup,
        "alwaysPullPatterns": args.alwaysPullPatterns,
        "imageCreationDateCondition": args.imageCreationDateCondition,
        "lastupdate": args.lastupdate,
        "name": args.name,
        "options": args.options,
        "pullImageAge": args.pullImageAge,
        "pullImageCount": args.pullImageCount,
        "pullImageTagPatterns": args.pullImageTagPatterns,
        "pullRepoPatternsExcludeds": args.pullRepoPatternsExcludeds,
        "registryScanTimeout": args.registryScanTimeout,
        "scannerNames": args.scannerNames,
        "scannerType": args.scannerType,
        "webhooks": args.webhooks,
    }, opts);
}

/**
 * A collection of arguments for invoking getIntegrationRegistry.
 */
export interface GetIntegrationRegistryArgs {
    advancedSettingsCleanup?: boolean;
    alwaysPullPatterns?: string[];
    imageCreationDateCondition?: string;
    lastupdate?: number;
    name: string;
    options?: inputs.GetIntegrationRegistryOption[];
    pullImageAge?: string;
    pullImageCount?: number;
    pullImageTagPatterns?: string[];
    pullRepoPatternsExcludeds?: string[];
    registryScanTimeout?: number;
    scannerNames?: string[];
    scannerType?: string;
    webhooks?: inputs.GetIntegrationRegistryWebhook[];
}

/**
 * A collection of values returned by getIntegrationRegistry.
 */
export interface GetIntegrationRegistryResult {
    readonly advancedSettingsCleanup?: boolean;
    readonly alwaysPullPatterns?: string[];
    readonly autoCleanup: boolean;
    readonly autoPull: boolean;
    readonly autoPullInterval: number;
    readonly autoPullMax: number;
    readonly autoPullRescan: boolean;
    readonly autoPullTime: string;
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly imageCreationDateCondition: string;
    readonly lastupdate: number;
    readonly name: string;
    readonly options?: outputs.GetIntegrationRegistryOption[];
    readonly password: string;
    readonly prefixes: string[];
    readonly pullImageAge: string;
    readonly pullImageCount: number;
    readonly pullImageTagPatterns?: string[];
    readonly pullRepoPatternsExcludeds?: string[];
    readonly registryScanTimeout?: number;
    readonly scannerNames: string[];
    readonly scannerType: string;
    readonly type: string;
    readonly url: string;
    readonly username: string;
    readonly webhooks?: outputs.GetIntegrationRegistryWebhook[];
}
/** @deprecated aquasec.index/getintegrationregistry.getIntegrationRegistry has been deprecated in favor of aquasec.index/getintegrationregistries.getIntegrationRegistries */
export function getIntegrationRegistryOutput(args: GetIntegrationRegistryOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIntegrationRegistryResult> {
    return pulumi.output(args).apply((a: any) => getIntegrationRegistry(a, opts))
}

/**
 * A collection of arguments for invoking getIntegrationRegistry.
 */
export interface GetIntegrationRegistryOutputArgs {
    advancedSettingsCleanup?: pulumi.Input<boolean>;
    alwaysPullPatterns?: pulumi.Input<pulumi.Input<string>[]>;
    imageCreationDateCondition?: pulumi.Input<string>;
    lastupdate?: pulumi.Input<number>;
    name: pulumi.Input<string>;
    options?: pulumi.Input<pulumi.Input<inputs.GetIntegrationRegistryOptionArgs>[]>;
    pullImageAge?: pulumi.Input<string>;
    pullImageCount?: pulumi.Input<number>;
    pullImageTagPatterns?: pulumi.Input<pulumi.Input<string>[]>;
    pullRepoPatternsExcludeds?: pulumi.Input<pulumi.Input<string>[]>;
    registryScanTimeout?: pulumi.Input<number>;
    scannerNames?: pulumi.Input<pulumi.Input<string>[]>;
    scannerType?: pulumi.Input<string>;
    webhooks?: pulumi.Input<pulumi.Input<inputs.GetIntegrationRegistryWebhookArgs>[]>;
}
